name: MassBreakDetector
version: '${project.version}'
main: com.github.kisaragieffective.massbreakdetector.Massbreakdetector
authors: [ KisaragiEffective ]
description: No more mass break. We had enough.
